services:
  db:
    image: postgis/postgis:15-3.3
    container_name: maritime_db
    environment:
      POSTGRES_USER: maritime
      POSTGRES_PASSWORD: maritime_pass
      POSTGRES_DB: maritime_intelligence
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maritime -d maritime_intelligence"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: